### ISSUE TITLE
Indicate main repository for vertical-cooperative

### ISSUE THREAD

**Issue by sseerrggii** [houssine78/vertical-cooperative#16]
Hi @houssine78 ! I was following this repository, @vdewulf told me that it was avaible for Odoo v12, and I noticed that main repo is https://github.com/coopiteasy/vertical-cooperative is it right?

I suggest to indicate main repo on this Readme! 

I also suggest to improve https://github.com/coopiteasy/vertical-cooperative Readme, can you open issues for this repo? We want to contribute  :pray:

**Comment by houssine78** [comment]
Hi @sseerrggii !

Yes you're right ! 

I've marked the repo as deprecated and I've opened the issues on the new repo.
